shapes: Arc through
johannes-wolf/cetz pull request #273
Opened 2023-10-22 17:37 UTC by johannes-wolf

Fixes #206. Thanks to @matthew-e-brown for the initial implementation!

2023-11-20 07:11 UTC, johannes-wolf commented
Rebased. We need to either merge #274 into this or onto 0.2.0 before merging this.

2023-11-22 19:04 UTC, fenjalien requested changes
What happens when a b c are in a striaght line? I'm guessing a divide by 0 happens somewhere, but could we have the panic message more verbose that it was arc-through? A check might need to be added before `calculate-circle-center-3pt`.

Update the changelog too

2023-11-22 19:04 UTC, fenjalien commented on src/draw/shapes.typ
> +  let b-is-left = side-on-line(a, c, b) < 0
I'm probably missing some context as the function docs are yet to be added but could you add comments explaining this?

2023-11-22 20:47 UTC, johannes-wolf commented on src/draw/shapes.typ
I have added documentation + explanation of the calculation.

2023-12-04 19:30 UTC, merged