doc: Manual 0.2.0
johannes-wolf/cetz pull request #301
Opened 2023-10-28 12:02 UTC by johannes-wolf

This updates the manual:
- Add a title page
- Change the TOC to a two column layout (we have quite short headings, so there was a lot of wasted horizontal space)
- Improve examples (#296)
- Add group anchor explanation

This also fixes two bugs in `coordinates.typ`:
- We should allow zero distance lerp, i.e. `(a, .5, a)` without failing (div. by zero) but returnung `a`. This is useful when doing calculations depending on anchors.
- The coordinate systems "|-" and "-|" must not update the current coordinate to `a` or `b` when resolving the both sides.

2023-10-28 12:04 UTC, johannes-wolf commented
@fenjalien What do you think? I want to have a nicer looking title page for the manual.

2023-10-28 14:08 UTC, fenjalien requested changes
Looks cool! Do you think we could show some examples/demos on the title? It would be even better to come up with an icon, something like typst guy, but thats much harder.

Also either you have more blockers on this PR or you've messed up your history as you've got changes to charts in here...

2023-10-28 14:12 UTC, johannes-wolf commented on manual.typ
> +  pagebreak(weak: true)
History is fucked up. I will rebase after the anchor branch got merged.

2023-10-28 14:25 UTC, johannes-wolf commented
> Looks cool! Do you think we could show some examples/demos on the title? It would be even better to come up with an icon, something like typst guy, but thats much harder.
> 
> Also either you have more blockers on this PR or you've messed up your history as you've got changes to charts in here...

Yes, examples would be nice. But what should we show? @JamesxX, any ideas?

2023-10-28 14:33 UTC, johannes-wolf commented on manual.typ
> +})
Yes, we should add this for all elements. I just wanted to have at least one example image.

2023-10-31 23:57 UTC, fenjalien approved these changes

2023-11-01 00:10 UTC, merged