transform: Add transform function
johannes-wolf/cetz pull request #324
Opened 2023-11-10 02:31 UTC by johannes-wolf

- Adds a new `transform(matrix)` function for setting or resetting the transformation matrix
- Changes `rotate` to take a single angle or a set of named arguments of one of the lists: x, y, z or yaw, pitch, roll to create a rotation matrix

2023-11-11 16:08 UTC, fenjalien requested changes

2023-11-11 16:08 UTC, fenjalien commented on src/draw/transformations.typ
> +#let transform(mat) = {
I would prefer the function name `set-transformation` given it sets the current transformation matrix. `transform` suggests that it applies the given matrix to the current transformation

2023-11-11 16:08 UTC, fenjalien commented on src/draw/transformations.typ
> +      assert.eq(mat.len(), 4,
this should be checked outside the returned function

2023-11-11 16:08 UTC, fenjalien commented on src/draw/transformations.typ
> +    assert(names.all(n => n in ("x", "y", "z")),
Couldn't you just use `all` in the if statement? Then if the names are malformed you panic in the `else`? Also make sure to output what the given names were

2023-11-11 16:32 UTC, johannes-wolf commented
@fenjalien Applied all your remarks :)

2023-11-12 16:07 UTC, fenjalien commented on src/draw/transformations.typ
> +    message: "Rotate takes a single z-angle or angles (x, y, z or yaw, pitch, roll) as named arguments")
output incorrect value

2023-11-12 17:57 UTC, johannes-wolf commented
Updated the ref-images (rotation is now CCW) and added the bad values to the error messages.

2023-11-19 09:33 UTC, fenjalien approved these changes

2023-11-19 09:36 UTC, merged